version: '2'

volumes:
  redis:
  postgres:
  box:

services:
  postgres:
    container_name: postgres
    image: 'postgres:13.6-alpine'
    environment:
      - POSTGRES_DB=nosso_amigo_secreto
      - POSTGRES_USER=nosso_amigo_secreto
      - POSTGRES_PASSWORD=nosso_amigo_secreto
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    container_name: redis
    image: 'redis:5.0.14-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  mailcatcher:
    container_name: mailcatcher
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

  jobs:
    container_name: jobs
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command: bash start_jobs
    volumes:
      - '.:/nosso_amigo_secreto'
    volumes_from:
      - box

  app:
    container_name: app
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start
    ports:
      - '3000:3000'
    volumes:
      - '.:/nosso_amigo_secreto'
    volumes_from:
      - box

  box:
    container_name: box
    image: busybox
    volumes:
      - /box
